import { COLOR, FONT_SIZE, FONTS, SIZE } from '@utils/Constant';
import { Platform, StyleSheet } from 'react-native';

export const GlobalStyles = StyleSheet.create({
  bigLine: {
    backgroundColor: COLOR.grayLight,
    height: SIZE.moderateScale(8),
  },
  flexStyle: { flex: 1 },
  boldText: {
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
    color: COLOR.dark, // Changed from black to dark to match existing theme
    textTransform: 'capitalize',
  },
  borderHalfSize1: {
    borderColor: COLOR.walletGray, // mapped from borderColor
    borderWidth: SIZE.moderateScale(1.5),
  },
  borderSize1: {
    borderColor: COLOR.walletGray,
    borderWidth: SIZE.moderateScale(1),
  },
  borderSize2: {
    borderColor: COLOR.walletGray,
    borderWidth: SIZE.moderateScale(2),
  },
  primaryButton: {
    height: SIZE.moderateScale(42),
    backgroundColor: COLOR.primary,
    borderRadius: SIZE.moderateScale(10),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  primaryButtonText: {
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font15,
    color: COLOR.white,
    lineHeight: SIZE.moderateScale(16),
  },
  bottomSheetContainer: {
    borderTopLeftRadius: SIZE.moderateScale(20),
    borderTopRightRadius: SIZE.moderateScale(20),
    height: SIZE.moderateScale(300),
  },
  capitalizeTitle: {
    textTransform: 'capitalize',
  },
  capitalizeTitle1: {
    textTransform: 'capitalize',
  },
  cardContainer: {
    backgroundColor: COLOR.white,
    gap: SIZE.moderateScale(10),
    paddingHorizontal: SIZE.moderateScale(15),
    paddingVertical: SIZE.moderateScale(15),
  },
  cardContainerNew: {
    backgroundColor: COLOR.white,
    paddingBottom: SIZE.moderateScale(15),
  },
  categoryBtnText: {
    color: COLOR.primary,
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font11,
    lineHeight: SIZE.moderateScale(16),
    textTransform: 'capitalize',
  },
  categoryContainer: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLOR.primaryLight,
    borderRadius: SIZE.moderateScale(30),
    paddingHorizontal: SIZE.moderateScale(12),
    paddingVertical: SIZE.moderateScale(3),
  },
  container: {
    backgroundColor: COLOR.white,
    flex: 1,
    paddingHorizontal: SIZE.moderateScale(15),
  },
  containerMain: {
    backgroundColor: COLOR.white,
    flex: 1,
    paddingHorizontal: SIZE.moderateScale(10),
  },
  containerNoScroll: {
    backgroundColor: COLOR.white,
    flex: 1,
  },
  containerNoSpace: {
    backgroundColor: COLOR.white,
    flexGrow: 1,
  },
  countContainer: {
    alignItems: 'center',
    backgroundColor: COLOR.primaryLight100,
    borderColor: COLOR.walletGray,
    borderRadius: SIZE.moderateScale(20),
    borderWidth: SIZE.moderateScale(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: SIZE.moderateScale(8),
    minWidth: SIZE.moderateScale(70),
    padding: SIZE.moderateScale(5),
  },
  descTitleTx: {
    color: COLOR.darkGrey,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(22),
    // textAlign: 'justify',
  },
  errorMessage: {
    color: COLOR.error,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
    marginBottom: SIZE.moderateScale(18),
    marginTop: SIZE.moderateScale(-18),
    paddingHorizontal: SIZE.moderateScale(10),
    textAlign: 'left',
    width: '100%',
  },
  footerContainer: { marginVertical: SIZE.moderateScale(30) },
  headerTx: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font16,
    lineHeight: SIZE.moderateScale(24),
    flex: 1,
  },
  infoTitle: {
    color: COLOR.lightDark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font11,
    lineHeight: SIZE.moderateScale(13),
  },
  lightText: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(16),
    textTransform: 'capitalize',
  },
  line: {
    backgroundColor: COLOR.grayLight,
    height: SIZE.moderateScale(1),
  },
  mainContainer: {
    backgroundColor: COLOR.white,
    flex: 1,
  },
  messageText: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
    paddingHorizontal: SIZE.moderateScale(20),
    paddingVertical: SIZE.moderateScale(5),
    textAlign: 'center',
  },
  minusContainer: {
    alignItems: 'center',
    borderColor: COLOR.walletGray,
    borderRadius: SIZE.moderateScale(20),
    borderWidth: SIZE.moderateScale(1),
    height: SIZE.moderateScale(23),
    justifyContent: 'center',
    width: SIZE.moderateScale(23),
  },
  plusContainer: {
    alignItems: 'center',
    backgroundColor: COLOR.primary,
    borderColor: COLOR.walletGray,
    borderRadius: SIZE.moderateScale(20),
    borderWidth: SIZE.moderateScale(1),
    height: SIZE.moderateScale(23),
    justifyContent: 'center',
    width: SIZE.moderateScale(23),
  },
  plusMinusText: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  plusMinusText2: {
    color: COLOR.white,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  plusMinusTextNew: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  plusMinusTextNew2: {
    color: COLOR.white,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: SIZE.moderateScale(5),
  },
  rowLine: { alignItems: 'center', flexDirection: 'row' },
  scrollContainer: {
    flex: 1,
    paddingHorizontal:
      Platform.OS === 'ios' ? SIZE.moderateScale(20) : SIZE.moderateScale(0),
  },
  subContainer: {
    backgroundColor: COLOR.white,
    borderColor: COLOR.grayLight,
    borderRadius: SIZE.moderateScale(15),
    borderWidth: SIZE.moderateScale(1.5),
    gap: SIZE.moderateScale(10),
    marginBottom: SIZE.moderateScale(8),
    marginVertical: SIZE.moderateScale(5),
    paddingHorizontal: SIZE.moderateScale(15),
    paddingVertical: SIZE.moderateScale(15),
  },
  subTitleBoldTx: {
    color: COLOR.darkGrey,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
  },
  subTitleTx: {
    color: COLOR.darkGrey,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(16),
  },
  textBold10: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font10,
    lineHeight: SIZE.moderateScale(14),
  },
  textBold12: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
  },
  textBold13: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(17),
  },
  textBold14: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(19),
  },
  textBold16: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font16,
    lineHeight: SIZE.moderateScale(24),
  },
  textBold18: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font18,
    lineHeight: SIZE.moderateScale(26),
  },
  textBold20: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font20,
    lineHeight: SIZE.moderateScale(28),
  },
  textBold22: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font22,
    lineHeight: SIZE.moderateScale(30),
  },
  textBold24: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font24,
    lineHeight: SIZE.moderateScale(32),
  },
  textBold26: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font26,
    lineHeight: SIZE.moderateScale(36),
  },
  textBold30: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font30,
    lineHeight: SIZE.moderateScale(42),
  },
  textMedium9: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: SIZE.moderateScale(9),
    lineHeight: SIZE.moderateScale(13),
  },
  textMedium10: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font10,
    lineHeight: SIZE.moderateScale(14),
  },
  textMedium11: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font11,
    lineHeight: SIZE.moderateScale(15),
  },
  textMedium12: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
  },
  textMedium13: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(17),
  },
  textMedium14: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  textMedium16: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font16,
    lineHeight: SIZE.moderateScale(24),
  },
  textMedium20: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font20,
    lineHeight: SIZE.moderateScale(28),
  },
  textMedium22: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font22,
    lineHeight: SIZE.moderateScale(32),
  },
  textRegular10: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font10,
    lineHeight: SIZE.moderateScale(14),
  },
  textRegular11: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font11,
    lineHeight: SIZE.moderateScale(15),
  },
  textRegular12: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
  },
  textRegular13: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(17),
  },
  textRegular14: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  textRegular16: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font16,
    lineHeight: SIZE.moderateScale(24),
  },
  textRegular18: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font18,
    lineHeight: SIZE.moderateScale(26),
  },
  textRegular20: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font20,
    lineHeight: SIZE.moderateScale(28),
  },
  textRegular22: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansRegular,
    fontSize: FONT_SIZE.font22,
    lineHeight: SIZE.moderateScale(30),
  },
  textSemiBold9: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: SIZE.moderateScale(9),
    lineHeight: SIZE.moderateScale(13),
  },
  textSemiBold10: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font10,
    lineHeight: SIZE.moderateScale(14),
  },
  textSemiBold11: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font11,
    lineHeight: SIZE.moderateScale(15),
  },
  textSemiBold12: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font12,
    lineHeight: SIZE.moderateScale(16),
  },
  textSemiBold13: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font13,
    lineHeight: SIZE.moderateScale(17),
  },
  textSemiBold14: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
  },
  textSemiBold15: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font15,
    lineHeight: SIZE.moderateScale(20),
  },
  textSemiBold16: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font16,
    lineHeight: SIZE.moderateScale(24),
  },
  textSemiBold18: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font18,
    lineHeight: SIZE.moderateScale(26),
  },
  textSemiBold20: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font20,
    lineHeight: SIZE.moderateScale(28),
  },
  textSemiBold22: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font22,
    lineHeight: SIZE.moderateScale(30),
  },
  textSemiBold24: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font24, // Assumed since user calculation was generic
    lineHeight: SIZE.moderateScale(32),
  },
  titleContainer: {
    flex: 1,
    justifyContent: 'space-evenly',
    marginHorizontal: SIZE.moderateScale(10),
  },
  titleInfo: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font17,
    lineHeight: SIZE.moderateScale(20),
  },
  titleText: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold, // using Bold18 as base
    fontSize: FONT_SIZE.font18,
    lineHeight: SIZE.moderateScale(26),
    paddingVertical: SIZE.moderateScale(10),
    textAlign: 'center',
  },
  titleTx: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(16),
    textTransform: 'capitalize',
  },
  upperCaseTitle: {
    textTransform: 'uppercase',
  },
  walletBadge: {
    alignItems: 'center',
    backgroundColor: COLOR.success, // Assumed mapping for green
    borderColor: COLOR.walletGray,
    borderRadius: 6,
    borderWidth: 1,
    height: SIZE.moderateScale(18),
    justifyContent: 'center',
    minWidth: SIZE.moderateScale(48),
    position: 'absolute',
    right: SIZE.moderateScale(0),
    top: SIZE.moderateScale(3),
    zIndex: SIZE.moderateScale(100),
  },
  wrapperStyle: {
    backgroundColor: COLOR.semiDark, // Assumed mapping
  },
  qtyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLOR.white,
    borderRadius: SIZE.moderateScale(7),
    paddingHorizontal: SIZE.moderateScale(2),
    paddingVertical: SIZE.moderateScale(2),
  },
  qtyFullContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLOR.white,
    borderRadius: SIZE.moderateScale(5),
    paddingHorizontal: SIZE.moderateScale(3),
    paddingVertical: SIZE.moderateScale(3),
    flex: 1,
    marginTop: SIZE.moderateScale(10),
  },
  qtyButton: {
    backgroundColor: COLOR.grayLight,
    borderRadius: SIZE.moderateScale(6),
    width: SIZE.moderateScale(24),
    height: SIZE.moderateScale(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyListButton: {
    backgroundColor: COLOR.primary,
    borderRadius: SIZE.moderateScale(6),
    width: SIZE.moderateScale(26),
    height: SIZE.moderateScale(26),
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtySymbol: {
    color: COLOR.primary,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(19),
  },
  qtyText: {
    color: COLOR.dark, // Changed from black
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
    minWidth: SIZE.moderateScale(24),
    textAlign: 'center',
  },
  qtyFullText: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansSemiBold,
    fontSize: FONT_SIZE.font14,
    lineHeight: SIZE.moderateScale(18),
    textAlign: 'center',
    flex: 1,
  },
  textMedium15: {
    fontFamily: FONTS.parkinsansMedium,
    fontSize: FONT_SIZE.font15,
    lineHeight: SIZE.moderateScale(20),
  },
  textBold15: {
    color: COLOR.dark,
    fontFamily: FONTS.parkinsansBold,
    fontSize: FONT_SIZE.font15,
    lineHeight: SIZE.moderateScale(20),
  },
});
